// Generated by CoffeeScript 1.10.0
var OSTN02C, arrow, degFmt, displayGeoid, displayGps, displayOsgb, dmsChanged, formatAlt, formatEOrN, formatLatOrLon, gpsChanged, gpsFields, id, input, j, l, len, len1, len2, loadData, m, osgbChanged, osgbFields, parseAlt, parseEorN, parseLatOrLon, ref, saveData, showMissing,
  indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

ref = ['e', 'n', 'mslAlt', 'datum', 'lat', 'lon', 'gpsAlt', 'dms', 'dec'];
for (j = 0, len = ref.length; j < len; j++) {
  id = ref[j];
  self[id + 'Field'] = get({
    id: id
  });
}

osgbFields = [eField, nField, mslAltField, datumField];

gpsFields = [lonField, latField, gpsAltField];

degFmt = get({
  id: 'inputs'
}).elements.degFmt;

arrow = get({
  id: 'arrow'
});

parseLatOrLon = function(s, isLat) {
  var dec, deg, dir, dms, maxVal, min, ref1, ref2, ref3, sec, value;
  dec = s.match(/^\s*-?([0-9]+|[0-9]+\.[0-9]*|[0-9]*\.[0-9]+)\s*$/);
  if (dec) {
    value = parseFloat(s);
  } else {
    dms = s.match(/^\s*([NESW])?\s*([0-9]+)(([^0-9]+([0-9]+))([^0-9]+([0-9]+|[0-9]+\.[0-9]*|[0-9]*\.[0-9]+))?)?[^NESW0-9]*([NESW])?\s*$/i);
    if (!dms) {
      return null;
    }
    deg = parseInt(dms[2]);
    min = parseInt((ref1 = dms[5]) != null ? ref1 : '0');
    sec = parseFloat((ref2 = dms[7]) != null ? ref2 : '0');
    if (min >= 60 || sec >= 60) {
      return null;
    }
    if ((dms[1] == null) && (dms[8] == null)) {
      return null;
    }
    if ((dms[1] != null) && (dms[8] != null)) {
      return null;
    }
    dir = ((ref3 = dms[1]) != null ? ref3 : dms[8]).toUpperCase();
    if ((isLat && (dir !== 'N' && dir !== 'S')) || ((!isLat) && (dir !== 'E' && dir !== 'W'))) {
      return null;
    }
    value = OSTN02C.decimalFromDegMinSec({
      deg: deg,
      min: min,
      sec: sec,
      westOrSouth: dir === 'W' || dir === 'S'
    });
  }
  maxVal = isLat ? 90 : 180;
  if (value < -maxVal || value > maxVal) {
    return null;
  }
  return value;
};

parseEorN = function(s) {
  var validFormat;
  validFormat = s.match(/^\s*-?([0-9]+|[0-9]+\.[0-9]*|[0-9]*\.[0-9]+)\s*$/);
  if (validFormat) {
    return parseFloat(s);
  } else {
    return null;
  }
};

parseAlt = function(s) {
  var validFormat;
  validFormat = s.match(/^\s*-?([0-9]+|[0-9]+\.[0-9]*|[0-9]*\.[0-9]+)\s*m?\s*$/);
  if (validFormat) {
    return parseFloat(s);
  } else {
    return null;
  }
};

formatLatOrLon = function(v, isLat) {
  var dir, dms;
  if (degFmt.value === 'dms') {
    dms = OSTN02C.degMinSecFromDecimal(v);
    dir = isLat ? (dms.westOrSouth ? 'S' : 'N') : (dms.westOrSouth ? 'W' : 'E');
    return dms.deg + "\u00b0\u2008" + dms.min + "\u2032\u2008" + (dms.sec.toFixed(2)) + "\u2033 " + dir;
  } else {
    return v.toFixed(6);
  }
};

formatEOrN = function(v) {
  return v.toFixed(0);
};

formatAlt = function(alt) {
  return (Math.round(alt)) + 'm';
};

showMissing = function(inputs) {
  var input, l, len1, results;
  results = [];
  for (l = 0, len1 = inputs.length; l < len1; l++) {
    input = inputs[l];
    results.push(input.value = "—");
  }
  return results;
};

displayGps = function(latLon) {
  if (latLon != null) {
    latField.value = formatLatOrLon(latLon.lat, true);
    lonField.value = formatLatOrLon(latLon.lon, false);
    return gpsAltField.value = formatAlt(latLon.elevation);
  } else {
    return showMissing(gpsFields);
  }
};

displayOsgb = function(en) {
  displayGeoid(en);
  if (en != null) {
    eField.value = formatEOrN(en.e);
    nField.value = formatEOrN(en.n);
    return mslAltField.value = formatAlt(en.elevation);
  } else {
    return showMissing(osgbFields);
  }
};

displayGeoid = function(en) {
  var geoidCaption, geoidName, geoidRegion;
  if (en != null) {
    geoidName = OSTN02C.geoidNameForIndex(en.geoid);
    geoidRegion = OSTN02C.geoidRegionForIndex(en.geoid);
    geoidCaption = geoidRegion + (geoidName === geoidRegion ? '' : " (" + geoidName + ")");
    return datumField.innerHTML = geoidCaption;
  } else {
    return datumField.innerHTML = "—";
  }
};

osgbChanged = function() {
  var e, elevation, enETRS89, i, input, l, len1, n, ref1, s, strs, values;
  strs = (function() {
    var l, len1, ref1, results;
    ref1 = osgbFields.slice(0, 3);
    results = [];
    for (l = 0, len1 = ref1.length; l < len1; l++) {
      input = ref1[l];
      results.push(input.value);
    }
    return results;
  })();
  values = (function() {
    var l, len1, results;
    results = [];
    for (i = l = 0, len1 = strs.length; l < len1; i = ++l) {
      s = strs[i];
      results.push(i === 2 ? parseAlt(s) : parseEorN(s));
    }
    return results;
  })();
  ref1 = osgbFields.slice(0, 3);
  for (i = l = 0, len1 = ref1.length; l < len1; i = ++l) {
    input = ref1[i];
    cls(input, values[i] != null ? {
      remove: 'invalid'
    } : {
      add: 'invalid'
    });
  }
  if (indexOf.call(values, null) >= 0) {
    displayGps(null);
    displayGeoid(null);
    return;
  }
  e = values[0], n = values[1], elevation = values[2];
  enETRS89 = OSTN02C.ETRS89EastingNorthingFromOSGB36EastingNorthing({
    e: e,
    n: n,
    elevation: elevation,
    geoid: 0
  });
  if (enETRS89.geoid === 0) {
    displayGps(null);
    displayGeoid(enETRS89);
    return;
  }
  displayGeoid(enETRS89);
  displayGps(OSTN02C.ETRS89LatLonFromETRS89EastingNorthing(enETRS89));
  arrow.style.visibility = 'visible';
  arrow.style.transform = 'scaleX(1)';
  return saveData('coords', {
    changed: 'osgb',
    values: strs
  });
};

gpsChanged = function() {
  var elevation, en, i, input, l, lat, len1, lon, s, strs, values;
  strs = (function() {
    var l, len1, results;
    results = [];
    for (l = 0, len1 = gpsFields.length; l < len1; l++) {
      input = gpsFields[l];
      results.push(input.value);
    }
    return results;
  })();
  values = (function() {
    var l, len1, results;
    results = [];
    for (i = l = 0, len1 = strs.length; l < len1; i = ++l) {
      s = strs[i];
      results.push(i === 2 ? parseAlt(s) : parseLatOrLon(s, i === 1));
    }
    return results;
  })();
  for (i = l = 0, len1 = gpsFields.length; l < len1; i = ++l) {
    input = gpsFields[i];
    cls(input, values[i] != null ? {
      remove: 'invalid'
    } : {
      add: 'invalid'
    });
  }
  if (indexOf.call(values, null) >= 0) {
    displayOsgb(null);
    return;
  }
  lon = values[0], lat = values[1], elevation = values[2];
  en = OSTN02C.OSGB36EastingNorthingFromETRS89EastingNorthing(OSTN02C.ETRS89EastingNorthingFromETRS89LatLon({
    lat: lat,
    lon: lon,
    elevation: elevation
  }));
  if (en.geoid === 0) {
    displayOsgb(null);
    displayGeoid(en);
    return;
  }
  displayOsgb(en);
  arrow.style.visibility = 'visible';
  arrow.style.transform = 'scaleX(-1)';
  return saveData('coords', {
    changed: 'gps',
    values: strs
  });
};

dmsChanged = function() {
  var field, i, isLat, l, len1, ref1, value;
  ref1 = [lonField, latField];
  for (i = l = 0, len1 = ref1.length; l < len1; i = ++l) {
    field = ref1[i];
    isLat = i === 1;
    value = parseLatOrLon(field.value, isLat);
    if (value) {
      field.value = formatLatOrLon(value, isLat);
    }
  }
  return saveData('degFmt', degFmt.value);
};

saveData = function(k, v) {
  var ref1;
  return (ref1 = self.localStorage) != null ? ref1.setItem(k, JSON.stringify(v)) : void 0;
};

loadData = function(k) {
  var ref1;
  return JSON.parse((ref1 = self.localStorage) != null ? ref1.getItem(k) : void 0);
};

for (l = 0, len1 = osgbFields.length; l < len1; l++) {
  input = osgbFields[l];
  input.oninput = osgbChanged;
}

for (m = 0, len2 = gpsFields.length; m < len2; m++) {
  input = gpsFields[m];
  input.oninput = gpsChanged;
}

decField.onclick = dmsField.onclick = dmsChanged;

OSTN02C = OSTN02CFactory(null, null, null, function() {
  var fields, i, len3, o, prevData, prevDegFmt, ref1, ref2, ref3, value;
  prevDegFmt = (ref1 = loadData('degFmt')) != null ? ref1 : 'dms';
  degFmt.value = prevDegFmt;
  prevData = (ref2 = loadData('coords')) != null ? ref2 : {
    changed: 'osgb',
    values: ['200000', '200000', '20m']
  };
  fields = prevData.changed === 'osgb' ? osgbFields : gpsFields;
  ref3 = prevData.values;
  for (i = o = 0, len3 = ref3.length; o < len3; i = ++o) {
    value = ref3[i];
    fields[i].value = value;
  }
  if (prevData.changed === 'osgb') {
    osgbChanged();
  } else {
    gpsChanged();
  }
  return dmsChanged();
});

//# sourceMappingURL=convert.js.map
